services:
  postgres:
    image: postgres:17.4-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    user: ${POSTGRES_USER}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - local_network
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    depends_on:
      - postgres
      - ml_service
    image: fastapi_app
    volumes:
      - ./backend/src:/backend/src
      - ./backend/migration:/backend/migration
    env_file:
      - ./backend/.env
    networks:
      - local_network
    ports:
      - '127.0.0.1:8020:8000'
    build:
      context: ./backend
      dockerfile: Dockerfile
    pull_policy: build
    entrypoint: sh -c "./src/start.sh"
    environment:
      - ML_SERVICE_URL=http://ml_service:8000

  ml_service:
    build:
      context: ./model
      dockerfile: Dockerfile
    networks:
      - local_network
    ports:
      - '127.0.0.1:8030:8000'
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./model/src:/app/src


networks:
  local_network:
    name: local_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.16.0.0/16

volumes:
  db_data:
